#!/bin/bash
awk '
/<!-- Notes Section -->/ {
    print "                        <!-- Riwayat Pembayaran -->"
    print "                        <div class=\"mt-4 border p-3 rounded bg-light mb-4\">"
    print "                            <h5 class=\"mb-3\"><i class=\"fas fa-history me-2 text-primary\"></i>Riwayat Pembayaran</h5>"
    print "                            <div class=\"table-responsive\">"
    print "                                <table class=\"table table-sm table-bordered\">"
    print "                                    <thead class=\"table-secondary\">"
    print "                                        <tr>"
    print "                                            <th>Waktu</th>"
    print "                                            <th>Keterangan</th>"
    print "                                            <th class=\"text-end\">Nominal</th>"
    print "                                        </tr>"
    print "                                    </thead>"
    print "                                    <tbody>"
    print "                                        @forelse($riwayatPembayaran as $riwayat)"
    print "                                            <tr>"
    print "                                                <td>{{ \\Carbon\\Carbon::parse($riwayat->tanggal_bayar)->format(\"d M Y H:i\") }}</td>"
    print "                                                <td>{{ $riwayat->keterangan }}</td>"
    print "                                                <td class=\"text-end fw-bold text-success\">Rp {{ number_format($riwayat->jumlah_bayar, 0, \",\", \".\") }}</td>"
    print "                                            </tr>"
    print "                                        @empty"
    print "                                            <tr><td colspan=\"3\" class=\"text-center text-muted\">Belum ada riwayat pembayaran</td></tr>"
    print "                                        @endforelse"
    print "                                        <tr>"
    print "                                            <td colspan=\"2\" class=\"text-end fw-bold\">Sisa Tagihan</td>"
    print "                                            <td class=\"text-end fw-bold text-danger\">Rp {{ number_format(max(0, $transaksi->total_harga - $transaksi->bayar), 0, \",\", \".\") }}</td>"
    print "                                        </tr>"
    print "                                    </tbody>"
    print "                                </table>"
    print "                            </div>"
    print ""
    print "                            @if($transaksi->status_pembayaran != \"Sudah Dibayar\")"
    print "                            <div class=\"text-end mt-2\">"
    print "                                <button type=\"button\" class=\"btn btn-success btn-sm\" data-bs-toggle=\"modal\" data-bs-target=\"#modalBayar\">"
    print "                                    <i class=\"fas fa-plus-circle me-1\"></i> Tambah Pembayaran"
    print "                                </button>"
    print "                            </div>"
    print "                            @endif"
    print "                        </div>"
    print ""
}
{ print }
/@endsection/ {
    print ""
    print "<!-- Modal Tambah Pembayaran -->"
    print "@if($transaksi->status_pembayaran != \"Sudah Dibayar\")"
    print "<div class=\"modal fade\" id=\"modalBayar\" tabindex=\"-1\" aria-hidden=\"true\">"
    print "    <div class=\"modal-dialog\">"
    print "        <div class=\"modal-content\">"
    print "            <div class=\"modal-header bg-success text-white\">"
    print "                <h5 class=\"modal-title\">Bayar Sisa Tagihan</h5>"
    print "                <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>"
    print "            </div>"
    print "            <form action=\"{{ route(\"transaksi.bayar\", $transaksi->id) }}\" method=\"POST\">"
    print "                @csrf"
    print "                <div class=\"modal-body\">"
    print "                    <div class=\"mb-3\">"
    print "                        <label class=\"form-label\">Sisa Tagihan Saat Ini</label>"
    print "                        <input type=\"text\" class=\"form-control\" value=\"Rp {{ number_format(max(0, $transaksi->total_harga - $transaksi->bayar), 0, \",\", \".\") }}\" readonly>"
    print "                    </div>"
    print "                    <div class=\"mb-3\">"
    print "                        <label class=\"form-label\">Nominal Pembayaran <span class=\"text-danger\">*</span></label>"
    print "                        <div class=\"input-group\">"
    print "                             <span class=\"input-group-text\">Rp</span>"
    print "                             <input type=\"number\" name=\"jumlah_bayar\" class=\"form-control\" min=\"1\" placeholder=\"Masukkan jumlah bayar\" required>"
    print "                        </div>"
    print "                    </div>"
    print "                </div>"
    print "                <div class=\"modal-footer\">"
    print "                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Batal</button>"
    print "                    <button type=\"submit\" class=\"btn btn-success\">Simpan Pembayaran</button>"
    print "                </div>"
    print "            </form>"
    print "        </div>"
    print "    </div>"
    print "</div>"
    print "@endif"
}
' resources/views/transaksi/show.blade.php > resources/views/transaksi/show_temp.blade.php
mv resources/views/transaksi/show_temp.blade.php resources/views/transaksi/show.blade.php
